# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "kubotat-tfstate"
    key     = "cmn/base.tfstate"
    profile = "kubotat-terraform"
    region  = "ap-northeast-1"
  }
}
