# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = module.env.project.region
  profile = module.env.project.aws_profile
}

##グローバルリソース(主にCloudFront関連)向け
provider "aws" {
  # 参考
  # https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/v2.6.0/examples/complete/main.tf
  alias = "global"

  # CloudFront expects ACM resources in us-east-1 region only
  region = "us-east-1"

  # Make it faster by skipping something
  skip_get_ec2_platforms      = true
  skip_metadata_api_check     = false # profile利用に必要でした
  skip_region_validation      = true
  skip_credentials_validation = true

  profile = module.env.project.aws_profile
}

##nutaku版向け(オレゴンリージョン)
provider "aws" {
  alias  = "oregon"
  region = "us-west-2"

  skip_get_ec2_platforms      = true
  skip_metadata_api_check     = false
  skip_region_validation      = true
  skip_credentials_validation = true

  profile = module.env.project.aws_profile
}
