variable "env" {}
variable "name" {}
variable "container_insights" {}
variable "container_definitions" {}
variable "task_role_policy_arns" {}
variable "task_exec_role_policy_arns" {}
variable "scheduling_strategy" {}
variable "deployment_minimum_healthy_percent" {}
variable "deployment_maximum_percent" {}
variable "target_group_arn" {}
variable "container_name" {}
variable "container_port" {}
variable "health_check_grace_period_seconds" {}
variable "desired_count" {}
#variable "" {}
