# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "name" {
  description = "プロジェクト識別子"
  default     = "kubotat"
}

variable "region" {
  description = "メインリージョン"
  default     = "ap-northeast-1"
}

variable "aws_profile" {
  description = "AWSプロファイル"
  default     = "kubotat-terraform"
}
