# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
output "name" {
  description = "プロジェクト識別子"
  value       = "kubotat"
}

output "region" {
  description = "メインリージョン"
  value       = "ap-northeast-1"
}

output "key-pair" {
  description = "EC2の構築に共通で利用するキーペア"
  value       = "keypair-tokyo"
}

output "tags" {
  description = "作成したリソースに共通して付与するタグ"
  value = {
    Terraform = true
  }
}

output "domain" {
  description = "管理ドメイン"
  value       = {"main":"kubotat.ii-dev.dmmgames.com"}
}

output "aws_profile" {
  description = "AWSプロファイル"
  value       = "kubotat-terraform"
}
